### ISSUE TITLE
Add links to activities and news

### ISSUE THREAD

**Issue by Es7evam** [GANESH-ICMC/ganesh-website#14]
Most of the activities and news have some external material or website, but currently there's no link support on both of them.

An example of activity is:
![image](https://user-images.githubusercontent.com/21321464/96749676-7fd10800-13a1-11eb-9995-09d681ba6267.png)

It could be made in two different ways, adding a button or simply adding a href at the titlte and/or image of the activity/news.

**Comment by Mamoanwar97** [comment]
let me try this can you assign it to me?

**Comment by Es7evam** [comment]
Solved on PR #16
