### ISSUE TITLE
Make the activity cards have the same size

### ISSUE THREAD

**Issue by Es7evam** [GANESH-ICMC/ganesh-website#8]
As can be seen in the image below, the cards, which are `<li>` components, can have different sizes. It would be good to fix such that they can have the same size independently of the text size. 

![image](https://user-images.githubusercontent.com/21321464/92496903-2042e280-f1cf-11ea-833d-db19382d745c.png)

A way to do this would be to make all the cards be limited by the one with the biggest height over all of them or just the ones in the same line, if that's possible.

**Comment by Mamoanwar97** [comment]
i can solve this too, can you assign it to me?

**Comment by Es7evam** [comment]
Fixed my mamoanwar97 on PR #15
